workspace = { members = ["lab_1", "lab_10", "lab_11", "lab_2", "lab_3", "lab_4", "lab_5", "lab_6", "lab_7", "lab_8", "lab_9"] }

[package]
name = "POTS_Labs"
version = "0.1.0"
edition = "2024"

[dependencies]
